### ISSUE TITLE
When using `context.goNamed` sub-route, I get a failed assertion while navigating

### ISSUE THREAD

**Issue by kamalbanga** [csells/go_router#169]
```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/heroes.dart': Failed assertion: line 688 pos 12: '() {
      final Animation<double> initial = initialManifest.animation;
      assert(initial != null);
      final HeroFlightDirection type = initialManifest.type;
      assert(type != null);
      switch (type) {
        case HeroFlightDirection.pop:
          return initial.value == 1.0 && initialManifest.isUserGestureTransition
              // During user gesture transitions, the animation controller isn't
              // driving the reverse transition, but should still be in a previously
              // completed stage with the initial value at 1.0.
              ? initial.status == AnimationStatus.completed
              : initial.status == AnimationStatus.reverse;
        case HeroFlightDirection.push:
          return initial.value == 0.0 && initial.status == AnimationStatus.forward;
      }
    }()': is not true.
```

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub

When the exception was thrown, this was the stack: 
```
#2      _HeroFlight.start (package:flutter/src/widgets/heroes.dart:688:12)
#3      HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:1013:60)
#4      HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:934:11)
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1088:9)
#7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#11     _invoke (dart:ui/hooks.dart:166:10)
#12     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#13     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 5 frames from class _AssertionError and dart:async)
```

Code in my app
```
GoRoute(
            path: '/home',
            pageBuilder: (context, state) => MaterialPage<void>(
                  key: state.pageKey,
                  child: const MyDecks(),
                ),
            routes: [
              GoRoute(
                path: ':id',
                name: 'info',
                pageBuilder: (context, state) => MaterialPage<void>(
                  key: state.pageKey,
                  child: DeckInfo(
                    id: idFrom(state.params['id']!),
                  ),
                ),
              )
            ]),
```

Code for navigation: `context.goNamed('info', params: {'id': id});`

**Comment by kamalbanga** [comment]
BTW this only happens, the first time I'm navigating. It doesn't happen second time onwards. Maybe this is not a `go_router` issue bug Flutter issue.

**Comment by csells** [comment]
That's not enough code to debug unfortunately. Can you post the code for a minimal, run-able app?

**Comment by berbsd** [comment]
I am running into similar issues and it's been puzzling me for a couple of days, meaning the solution might actually be obvious but it somehow escapes me.  I would love if someone could provide some guidance on how to really debug the issue.  Here is some high-level description of the logic and hopefully someone can help

The app has the following stop

- AppBloc responds to firebase user auth changes. 
- Profile bloc is rebuilt when the user changes (contains the same user object as app bloc)

The issue occurs when the user display name is updated 

- User navigates to  Home > Profile > Settings > Change User Name (page)
- Once the user name is updated, all the blocs rebuild properly, however the app crash with the error above

**App Widget**

```dart
class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    final AppBloc _appBloc = context.read<AppBloc>();
    final GoRouter _router = GoRouter(
      debugLogDiagnostics: true,
      observers: [AppNavObserver()],
      routes: [...
      initialLocation: '/splash',
      redirect: (state) {...
      refreshListenable: GoRouterRefreshStream(_appBloc.stream),
      errorBuilder: (context, state) => ErrorView(message: '${state.error}'),
    );
    return BlocBuilder<AppBloc, AppState>(
      builder: (context, state) {
        // event added when the user changed. 
        context.read<ProfileBloc>().add(UserProfileChanged(state.user));

        return CupertinoApp.router(
          title: 'Flutter Demo',
          debugShowCheckedModeBanner: false,
          theme: const CupertinoThemeData(
            primaryColor: CupertinoColors.systemPurple,
          ),
          routeInformationParser: _router.routeInformationParser,
          routerDelegate: _router.routerDelegate,
        );
      },
    );
  }
}
```
 
**Routes (subset)**

```dart
GoRoute(
          path: '/home',
          builder: (context, state) => const HomeView(),
          routes: [
            GoRoute(
              path: 'confirm_email',
              builder: (context, state) => const ConfirmEmailView(),
            ),
          ],
        ),
        GoRoute(
          path: '/settings',
          name: 'settings',
          builder: (context, state) => const SettingsView(),
          routes: [
            GoRoute(
              path: 'profile',
              builder: (context, state) => const SettingsProfileView(),
              routes: [
                GoRoute(
                  path: 'name',
                  builder: (context, state) => SettingsProfileNameView(
                    initialValue: state.extra as String? ?? '',
                  ),
                ),
              ],
            ),
          ],
        ),

```

**Comment by csells** [comment]
Can you try wrapping your call to `context.goNamed()` in [a call to `scheduleMicrotask`](https://api.flutter.dev/flutter/dart-async/Zone/scheduleMicrotask.html)?

**Comment by berbsd** [comment]
That is a very good point. Will give it a shot. Thx!
